# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ae69cc88ccc2f229d0a3b1c673899e461df889f7f3ded6cfa28ba5c0bb1a783564663b5d4f81919186c286d73e06fa269f9b0122ec03a144b8840dff01dac49e

test:
  secret_key_base: 42dc4d04d87aabaa9cfc78958d333b9c434b51017dfad1d12bcc8ed61f625931802fda8313d7921f6cfe08761b16db19ff5c37542448e58fb5c692bcf2255743

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
